# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Fiona Geuß"

# A description of your site for meta tag, search engine results.
description: "Fiona Geuß (born 1981) is an art historian and received her Phd from Freie Universität Berlin in 2020. Her research topic concerns the dialogical artwork and forms of conversation in artistic practices since the 1970s. She was co-organizer of the event space Salon Populaire in Berlin Schöneberg (2010–2012). She organized seminars at the The Public School Berlin, an autodidactic, pedagogical framework founded by Telic Arts Exchange in Los Angeles in 2007 (2010-2015). She held lectures, participated in conferences and taught seminars, amongst others Forms/models of education and self-determination at nGbK Berlin, When exhibitions become politics at Friedrich Schiller Universität in Jena, and most recently at Carl von Ossietzky Universität in Oldenburg. In 2015 she co-founded the initiative A Public Library in Berlin. Since 2016 she is curator for communications at Hamburger Bahnhof – Museum für Gegenwart – Berlin."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://fionageuss.net/"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Categories
    url: /tags
  - text: About
    url: /about

# Colors
accent_color: '#1C1C82'

# Site footer
footer:
  content: "&copy; Fiona Geuß all rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 30
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
