# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Fiona Geuß"

# A description of your site for meta tag, search engine results.
description: "Fiona Geuß is an art historian and received her Phd from Freie Universität Berlin in 2020. Her research topic concerns the dialogical artwork and forms of conversation in artistic practices since the 1970s."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: "/fionageuss"

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://fionageuss.net"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Categories
    url: /tags
  - text: About
    url: /about

# Colors
accent_color: '#BD0089'

# Site footer
footer:
  content: "&copy; Fiona Geuß all rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 30
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
